### ISSUE TITLE
`ident` function is not primitive

### ISSUE THREAD

**Issue by ivg** [janestreet/core_kernel#25]
Core defines  [`ident`](https://github.com/janestreet/core_kernel/blob/master/lib/common.ml#L70) function available in the global namespace, as a regular OCaml function not as an "%identity" primitive. As a result  this doesn't allow certain kinds of optimization performed by a compiler, and may affect performance. 

`Fn.id` on the other hand is a primitive. 

Is it intended? If not then I can provide a PR to fix this.

**Comment by ivg** [comment]
it is actually fixed in some version. Now it is primitive everywhere

**Comment by bmillwood** [comment]
Huh, sorry for missing this issue earlier. If you're happy then I'm happy, but just looking over the git blame for core_kernel I don't think the definition of `ident` has changed in quite a while, so I'm surprised that this is fixed.

Well, bugs mysteriously disappearing is certainly better than them mysteriously appearing :)

**Comment by ivg** [comment]
Indeed, it wasn't fixed. For some reason, I forgot about the `mli`. In the `common.mli` it is still not defined as `"%identity"`

**Comment by bcc32** [comment]
Now it is just defined as `Fn.id`.  I don't know if it fixes the performance issue, though.

**Comment by ivg** [comment]
Now it's good, `Fn.id` is external, and `std_internal.ml` has no mli, so nothing will prevent compiler from seeing its primitivity. 

Thanks!
